version: "3"

tasks:
  generate: 
    desc: Generate Go code from protobuf
    cmds:
    - protoc --proto_path=. greet/proto/*.proto --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative